apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  # don't namespace proc
  hostPID: true
  containers:
  - name: nginx
    image: busybox
    securityContext:
      privileged: true
    command: [ "/bin/sh", "-c", "--" ]
    # What does this do?
    #
    # - Stops etcd dead in its tracks, but does not kill it
    # - Every 50 seconds, let etcd recover for 5 seconds
    #
    # Think of it as simulated exhaustion of CPU cyles, but without the load penalty
    args: [ "while true; do pkill -SIGSTOP etcd; echo honk; sleep 50; pkill -SIGCONT etcd; sleep 5; done" ]
