apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  hostPID: true
  containers:
  - name: nginx
    image: busybox
    securityContext:
      privileged: true
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do pkill -SIGSTOP etcd; echo honk; sleep 50; pkill -SIGCONT etcd; sleep 5; done" ]
